##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-notification-daemon
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libcanberra-ctk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libctk-3-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - libxml2-utils
    - quilt
    - shared-mime-info

    #required for cafe-common
    - autoconf
    - make

    #required for cafe-desktop
    - intltool
    - iso-codes
    - libglib2.0-doc
    - libtool

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev libcail-3-dev'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-notification-daemon/raw/master/data/icons/16x16/cafe-notification-properties.png; fi
