##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-notification-daemon
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libcafe-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - libxml2-utils
    - cafe-common
    - quilt
    - shared-mime-info

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-notification-daemon/raw/master/data/icons/16x16/cafe-notification-properties.png; fi
