.TH "cafe-notification-properties" "1" "2009-08-03"

.SH "NAME" 
cafe-notification-properties \- Set up the options for desktop notifications

.SH "SYNOPSIS"
.PP
.B cafe-notification-properties 

.SH "DESCRIPTION" 
.PP
This manual page documents briefly the \fBcafe-notification-properties\fR
command.
.PP
\fBcafe-notification-properties\fR is a utility to set up various
options related to desktop notifications. 

.SH "AUTHOR"
.PP
.B cafe-notification-properties was
written by Jonh Wendell <wendell@bani.com.br> and Perberos <perberos@gmail.com>.

This manual page was written by Francois Wendling <frwendling@free.fr> for the
notification-properties in Debian project (but may be used by others)
and adapted for CAFE by Stefano Karapetsas <stefano@karapetsas.com>.
